from django.contrib import admin
from django.urls import path

from application import views as application_views

urlpatterns = [
    path('', application_views.dashboard, name='dashboard'),
    path('cont/', application_views.account, name='account'),
    path('adaugare-disciplina-noua/', application_views.adaugareDisciplina, name='adaugareDisciplina'),
    path('stergere-disciplina-existenta/', application_views.stergereDisciplina, name='stergereDisciplina'),
    path('vizualizare-disciplina/<str:pk>', application_views.vizualizareDisciplina, name='vizualizareDisciplina'),
    path('vizualizare-disciplina/<str:pk>/adaugare-proiect-nou/', application_views.adaugareProiect,
         name='adaugareProiect'),
    path('vizualizare-disciplina/<str:pk>/vizualizare-proiecte/', application_views.vizualizareProiecte,
         name='vizualizareProiecte'),
    path('adugare-studenti/', application_views.adaugareStudenti, name='adaugareStudenti'),
    path('vizualizare-studenti/grupa/<str:pk>', application_views.vizualizareStudenti, name='vizualizareStudenti'),
    path('vizualizare-studenti/grupa/modificare-discipline/student/<str:pk>', application_views.modificareDiscipline,
         name='modeificareDiscipline'),
    path('stergere-cont-utilizator/', application_views.stergereCont, name='stergereCont'),
    path('adaugare-cont-utilizator/', application_views.adaugareCont, name='adaugareCont'),
    path('vizualizare-discipline/', application_views.vizualizareDiscipline, name='vizualizareDiscipline'),
    path('vizualizare-grupe/', application_views.vizulalizareGrupe, name='vizualizareGrupe'),
    path('vizualizare-grupe-studenti/', application_views.vizulalizareGrupeStudenti, name='vizualizareGrupeStudenti'),
    path('adaugare-grupa/', application_views.adaugareGrupa, name='adaugareGrupa'),
    path('vizualizare-grupe/asignare-discipline/<str:pk>', application_views.asignareDiscipline,
         name='asignareDiscipline'),
    path('vizualizare-disciplina/vizualizare-proiecte/proiect/<str:pk>', application_views.proiect,
         name='proiect'),
    path('vizualizare-disciplina/vizualizare-proiecte/proiect/<str:pk>/adaugareTema', application_views.adaugareTema,
         name='adaugareTema'),
    path('vizualizare-disciplina/<str:pk>/asignare-teme-studenti/', application_views.distribuireTeme,
         name='distribuireTeme'),
    path('disciplina-student/<str:pk>/', application_views.disciplinaStudent,
         name='disciplinaStudent'),
    path('disciplina-student/tema/<str:pk1>', application_views.temaStudent,
         name='temaStudent'),
    path('disciplina-student/tema/incarcare-intermediara-tema/<str:pk>', application_views.incarcareIntermediaraTema,
         name='incarcareIntermediaraTema'),
    path('disciplina-student/tema/incarcare-finala-tema/<str:pk>', application_views.incarcareFinalaTema,
         name='incarcareFinalaTema'),
    path('disciplina-student/tema/<str:pk1>/efectuare-task/<str:pk2>', application_views.efectuareTask,
         name='efectuareTask'),
    path('vizualizare-disciplina/vizualizare-proiecte/proiect/tema/<str:pk>', application_views.vizualizareTema,
         name='vizualizareTema'),
    path('vizualizare-disciplina/vizualizare-proiecte/proiect/tema/<str:pk1>/download/<str:pk2>',
         application_views.download, name='download'),
    path('vizualizare-disciplina/vizualizare-proiecte/proiect/tema/<str:pk>/adaugare-nota/',
         application_views.adaugareNota, name='adaugareNota'),
    path('vizualizare-disciplina/vizualizare-proiecte/proiect/tema/<str:pk>/creare-echipe',
         application_views.creareEchipe, name='creareEchipe'),
    path('vizualizare-disciplina/<str:pk>/catalog', application_views.catalog, name='catalog'),
    path('vizualizare-disciplina/<str:pk1>/catalog/grupa/<str:pk2>', application_views.vizualizareCatalog,
         name='vizualizareCatalog'),
    path('vizualizare-disciplina/<str:pk1>/catalog/grupa/<str:pk2>/descarcare-catalog',
         application_views.descarcareCatalog,  name='descarcareCatalog'),
    path('disciplina-student/<str:pk>/note/', application_views.note, name='note'),
]
