# Generated by Django 3.0.14 on 2022-01-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_project_ownerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='path',
        ),
        migrations.AddField(
            model_name='project',
            name='path',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PathProject',
        ),
    ]
