# Generated by Django 3.0.14 on 2022-02-28 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20220228_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='proiecte',
        ),
        migrations.AddField(
            model_name='proiect',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Disciplina'),
        ),
    ]
