# Generated by Django 3.0.14 on 2022-03-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20220228_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='an_universitar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='semestru',
            field=models.IntegerField(null=True),
        ),
    ]
