# Generated by Django 3.0.14 on 2022-03-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20220301_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='proiect',
            name='document',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
