# Generated by Django 3.0.14 on 2022-03-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_proiect_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proiect',
            old_name='data_inregistare',
            new_name='data_inregistrare',
        ),
    ]
