# Generated by Django 3.0.14 on 2022-03-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20220304_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='proiect',
            name='grupa',
            field=models.IntegerField(null=True),
        ),
    ]
