# Generated by Django 3.0.14 on 2022-03-05 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_proiect_grupa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proiect',
            old_name='grupa',
            new_name='nr_persoane',
        ),
    ]
