# Generated by Django 3.0.14 on 2022-03-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_student_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='nume',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
