# Generated by Django 3.0.14 on 2022-03-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20220305_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='proiect',
            name='distribuire_teme',
            field=models.BooleanField(default=False),
        ),
    ]
