# Generated by Django 3.0.14 on 2022-03-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_proiect_distribuire_teme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proiect',
            name='distribuire_teme',
            field=models.BooleanField(),
        ),
    ]
