# Generated by Django 3.0.14 on 2022-03-09 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_auto_20220306_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='discipline',
        ),
        migrations.CreateModel(
            name='Grupa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=10, null=True)),
                ('directie', models.CharField(max_length=10, null=True)),
                ('discipline', models.ManyToManyField(to='application.Disciplina')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='grupa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Grupa'),
        ),
    ]
