# Generated by Django 3.0.14 on 2022-03-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_auto_20220309_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupa',
            name='directie',
        ),
    ]
