# Generated by Django 3.0.14 on 2022-03-09 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_remove_grupa_directie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=100)),
                ('data_incarcare', models.DateField()),
                ('document', models.CharField(max_length=100)),
                ('proiect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Proiect')),
                ('static', models.ManyToManyField(to='application.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=100)),
                ('descriere', models.CharField(max_length=300)),
                ('efectuat', models.BooleanField()),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Tema')),
            ],
        ),
    ]
