# Generated by Django 3.0.14 on 2022-03-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_task_tema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tema',
            old_name='static',
            new_name='student',
        ),
    ]
