# Generated by Django 3.0.14 on 2022-03-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_auto_20220309_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='data_incarcare',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='document',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
