# Generated by Django 3.0.14 on 2022-03-10 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0022_auto_20220309_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='profesor',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='profesori',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
