# Generated by Django 3.0.14 on 2022-03-11 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_auto_20220310_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='data_incarcare',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='document',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='student',
        ),
        migrations.CreateModel(
            name='Incarcare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_incarcare', models.DateField(null=True)),
                ('document', models.CharField(max_length=100, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Student')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Tema')),
            ],
        ),
    ]
