# Generated by Django 3.0.14 on 2022-03-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_auto_20220311_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teme',
            field=models.ManyToManyField(to='application.Tema'),
        ),
    ]
