# Generated by Django 3.0.14 on 2022-03-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_remove_proiect_distribuire_teme'),
    ]

    operations = [
        migrations.AddField(
            model_name='incarcare',
            name='nota',
            field=models.FloatField(default=0),
        ),
    ]
