# Generated by Django 3.0.14 on 2022-03-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_incarcare_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='descriere',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
