# Generated by Django 3.0.14 on 2022-03-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_tema_descriere'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discipline',
            field=models.ManyToManyField(to='application.Disciplina'),
        ),
    ]
