# Generated by Django 3.0.14 on 2022-03-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_student_discipline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='discipline',
            new_name='discipline_modificate',
        ),
    ]
