# Generated by Django 3.0.14 on 2022-03-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_auto_20220325_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='discipline_modificate',
            new_name='discipline',
        ),
        migrations.RemoveField(
            model_name='grupa',
            name='discipline',
        ),
    ]
