# Generated by Django 3.0.14 on 2022-03-27 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_auto_20220327_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='profesori',
            field=models.ManyToManyField(to='application.Profesor'),
        ),
        migrations.AlterField(
            model_name='proiect',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Profesor'),
        ),
    ]
