# Generated by Django 3.0.14 on 2022-03-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0035_auto_20220327_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='grupe',
            field=models.ManyToManyField(to='application.Grupa'),
        ),
    ]
