# Generated by Django 3.0.14 on 2022-03-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0036_profesor_grupe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='grupe',
        ),
        migrations.RemoveField(
            model_name='student',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profesori',
        ),
    ]
