# Generated by Django 3.0.14 on 2022-03-31 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_disciplinaprofesorstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Echipa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Grupa')),
                ('studenti', models.ManyToManyField(to='application.Student')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Tema')),
            ],
        ),
    ]
