# Generated by Django 3.0.14 on 2022-03-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0039_echipa'),
    ]

    operations = [
        migrations.AddField(
            model_name='echipa',
            name='enume',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
