# Generated by Django 3.0.14 on 2022-03-31 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0040_echipa_enume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='echipa',
            old_name='enume',
            new_name='nume',
        ),
    ]
