# Generated by Django 3.0.14 on 2022-03-31 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0041_auto_20220331_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='echipa',
            name='proiect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Proiect'),
        ),
    ]
