# Generated by Django 3.0.14 on 2022-03-31 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0042_echipa_proiect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echipa',
            name='grupa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Grupa'),
        ),
    ]
