# Generated by Django 3.0.14 on 2022-06-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0043_auto_20220331_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='proiect',
            name='data_intermediara',
            field=models.DateField(default=None),
        ),
    ]
