# Generated by Django 3.0.14 on 2022-06-02 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_proiect_data_intermediara'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupaProiect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grupa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Grupa')),
                ('proiect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Proiect')),
            ],
        ),
    ]
