# Generated by Django 3.0.14 on 2022-06-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0046_auto_20220602_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='incarcare',
            name='tip',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
