# Generated by Django 3.0.14 on 2022-06-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0047_incarcare_tip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echipa',
            name='grupa',
        ),
    ]
