# Generated by Django 3.0.14 on 2022-06-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0048_remove_echipa_grupa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupa',
            name='nume',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
