# Generated by Django 3.0.14 on 2022-06-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0049_auto_20220628_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupa',
            name='asignare_discipline',
            field=models.BooleanField(default=False),
        ),
    ]
